runtime: nodejs20
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
env_variables:
  PORT: "8080"
handlers:
- url: /sketchpad/.*
  static_files: sketchpad/\1
  upload: sketchpad/.*
  mime_type: application/javascript
- url: /.*
  static_files: public/\1
  upload: public/.*